mkdir -p docs
cat > docs/docs.go << 'EOF'
// Package docs GENERATED BY SWAG; DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{}`

var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Subscription Aggregator API",
	Description:      "Сервис управления подписками пользователей.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
EOF
